
package org.sms.send_sms.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendSms", targetNamespace = "http://www.sms.org/send_sms/service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendSms {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.sms.send_sms.service.SendSmsResponse
     */
    @WebMethod
    @WebResult(name = "sendSmsResponse", targetNamespace = "http://www.sms.org/send_sms/service", partName = "result")
    public SendSmsResponse sendSms(
        @WebParam(name = "sendSmsRequest", targetNamespace = "http://www.sms.org/send_sms/service", partName = "parameters")
        SendSmsRequest parameters);

}
